name: Palestine Datasets

on:
  schedule:
    # Runs once every 24 hours, at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download JSON file
      run: |
        curl -o data.json "https://data.techforpalestine.org/api/v2/killed-in-gaza.min.json"

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions-bot@users.noreply.github.com"

    - name: Check for changes and commit
      id: commit_changes
      run: |
        git add data.json
        if git diff --cached --exit-code; then
          echo "No changes to commit."
          echo "committed=false" >> $GITHUB_OUTPUT
        else
          git commit -m "Automated: Update data.json"
          echo "committed=true" >> $GITHUB_OUTPUT
        fi

    - name: Push changes
      if: steps.commit_changes.outputs.committed == 'true'
      run: git push
